/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#ifndef AG_CYPHER_ADJACENCY_MATCH_H
#define AG_CYPHER_ADJACENCY_MATCH_H

#include "nodes/extensible.h"

#define AGE_ADJACENCY_MATCH_SCAN_NAME "AGE Adjacency Match"

typedef enum AgeAdjacencyMatchValueKind
{
    AGE_ADJACENCY_MATCH_VALUE_NONE = 0,
    AGE_ADJACENCY_MATCH_VALUE_CONST,
    AGE_ADJACENCY_MATCH_VALUE_RUNTIME_SLOT
} AgeAdjacencyMatchValueKind;

typedef enum AgeAdjacencyMatchTerminalStrategy
{
    AGE_ADJACENCY_MATCH_TERMINAL_STRATEGY_NONE = 0,
    AGE_ADJACENCY_MATCH_TERMINAL_STRATEGY_LABEL_PROPERTY,
    AGE_ADJACENCY_MATCH_TERMINAL_STRATEGY_LABEL_BLOCK,
    AGE_ADJACENCY_MATCH_TERMINAL_STRATEGY_PROPERTY_SOURCE,
    AGE_ADJACENCY_MATCH_TERMINAL_STRATEGY_PROPERTY_RECHECK
} AgeAdjacencyMatchTerminalStrategy;

typedef enum AgeAdjacencyMatchSourceHandoff
{
    AGE_ADJACENCY_MATCH_SOURCE_HANDOFF_POSTING_RUN = 0,
    AGE_ADJACENCY_MATCH_SOURCE_HANDOFF_LABEL_SLICE,
    AGE_ADJACENCY_MATCH_SOURCE_HANDOFF_PROPERTY_SET,
    AGE_ADJACENCY_MATCH_SOURCE_HANDOFF_LABEL_PROPERTY_INTERSECTION,
    AGE_ADJACENCY_MATCH_SOURCE_HANDOFF_RECHECK
} AgeAdjacencyMatchSourceHandoff;

typedef enum AgeAdjacencyMatchTerminalPrefetchReason
{
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_NONE = 0,
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_NOT_INDEXABLE,
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_EDGE_PAYLOAD_REQUIRED,
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_LARGE_TERMINAL_FANOUT,
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_SMALL_TERMINAL_FANOUT,
    AGE_ADJACENCY_MATCH_PREFETCH_REASON_PROPERTY_SOURCE_TOO_BROAD
} AgeAdjacencyMatchTerminalPrefetchReason;

typedef enum AgeAdjacencyMatchIndexKind
{
    AGE_ADJACENCY_MATCH_INDEX_UNKNOWN = 0,
    AGE_ADJACENCY_MATCH_INDEX_ADJACENCY,
    AGE_ADJACENCY_MATCH_INDEX_PROPERTY
} AgeAdjacencyMatchIndexKind;

typedef enum AgeAdjacencyMatchIndexDirection
{
    AGE_ADJACENCY_MATCH_INDEX_DIRECTION_NONE = 0,
    AGE_ADJACENCY_MATCH_INDEX_DIRECTION_OUT,
    AGE_ADJACENCY_MATCH_INDEX_DIRECTION_IN
} AgeAdjacencyMatchIndexDirection;

typedef enum AgeAdjacencyMatchDescriptorField
{
    AGE_ADJACENCY_MATCH_DESC_GRAPH_OID = 0,
    AGE_ADJACENCY_MATCH_DESC_EDGE_VARIABLE,
    AGE_ADJACENCY_MATCH_DESC_EDGE_PROPERTY_PREDICATE,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_LABEL_CONSTRAINT,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_PREDICATE,
    AGE_ADJACENCY_MATCH_DESC_EDGE_PAYLOAD_REQUIRED,
    AGE_ADJACENCY_MATCH_DESC_PAYLOAD_ATTR_MASK,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_LABEL_ID,
    AGE_ADJACENCY_MATCH_DESC_ENDPOINT_ATTNO,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_FANOUT,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_TERMINAL_FANOUT,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_COMPOSITE_FANOUT,
    AGE_ADJACENCY_MATCH_DESC_SOURCE_HANDOFF_KIND,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_SOURCE_FANOUT,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_SOURCE_BLOCKS,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_PROPERTY_SOURCE_MATCHES,
    AGE_ADJACENCY_MATCH_DESC_COMPOSITE_SELECTIVITY_PPM,
    AGE_ADJACENCY_MATCH_DESC_COMPOSITE_SELECTIVITY_SOURCE_KIND,
    AGE_ADJACENCY_MATCH_DESC_VALUE_POSTING_SOURCE_KIND,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_LABEL_GROUPS,
    AGE_ADJACENCY_MATCH_DESC_ESTIMATED_MAIN_BLOCKS,
    AGE_ADJACENCY_MATCH_DESC_FANOUT_SOURCE,
    AGE_ADJACENCY_MATCH_DESC_INDEX_SOURCE,
    AGE_ADJACENCY_MATCH_DESC_INDEX_KIND_ID,
    AGE_ADJACENCY_MATCH_DESC_INDEX_PROVIDER,
    AGE_ADJACENCY_MATCH_DESC_INDEX_DIRECTION_KIND,
    AGE_ADJACENCY_MATCH_DESC_INDEX_PROPERTY_COUNT,
    AGE_ADJACENCY_MATCH_DESC_INDEX_METADATA_BACKED,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_KEY,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_INDEX_OID,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_INDEX_SOURCE,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_INDEX_PROVIDER,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_INDEX_TYPE,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_INDEX_METADATA_BACKED,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_PREFETCH_ELIGIBLE,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_VALUE_KIND,
    AGE_ADJACENCY_MATCH_DESC_TERMINAL_SOURCE_STRATEGY,
    AGE_ADJACENCY_MATCH_DESC_TERMINAL_PREFETCH_THRESHOLD,
    AGE_ADJACENCY_MATCH_DESC_TERMINAL_PREFETCH_REASON_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_COMPONENT,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_CONNECTOR_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_BOUND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_PROPERTY_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_SOURCE_EVIDENCE,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_SOURCE_KIND_ID,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_SOLVED_RELIDS,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_CANDIDATE_COUNT,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_DECLARED_COVER_COUNT,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_COVER_MATCH_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_NEXT_CONNECTOR_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_NEXT_PROPERTY_KIND,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_NEXT_SOURCE_EVIDENCE,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_NEXT_ROWS,
    AGE_ADJACENCY_MATCH_DESC_JOIN_ORDER_NEXT_TOTAL_COST,
    AGE_ADJACENCY_MATCH_DESC_PARALLEL_SAFE,
    AGE_ADJACENCY_MATCH_DESC_PARALLEL_AWARE,
    AGE_ADJACENCY_MATCH_DESC_PARALLEL_WORKERS,
    AGE_ADJACENCY_MATCH_DESC_PARALLEL_GATHER_COST,
    AGE_ADJACENCY_MATCH_DESC_ORDER_PRESERVING,
    AGE_ADJACENCY_MATCH_DESC_SHARED_STATE_REQUIRED,
    AGE_ADJACENCY_MATCH_DESC_RIGHT_PROPERTY_VALUE,
    AGE_ADJACENCY_MATCH_DESC_COUNT
} AgeAdjacencyMatchDescriptorField;

extern const CustomScanMethods age_adjacency_match_scan_methods;
extern const char *age_adjacency_match_index_kind_name(
    AgeAdjacencyMatchIndexKind kind);
extern const char *age_adjacency_match_index_direction_name(
    AgeAdjacencyMatchIndexDirection direction);
extern const char *age_adjacency_match_terminal_prefetch_reason_name(
    AgeAdjacencyMatchTerminalPrefetchReason reason);
extern const char *age_adjacency_match_source_handoff_name(
    AgeAdjacencyMatchSourceHandoff handoff);

#endif
